version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  postgres-app:
    image: postgres:15
    environment:
      - POSTGRES_DB=${APP_POSTGRES_DB}
      - POSTGRES_USER=${APP_POSTGRES_USER}
      - POSTGRES_PASSWORD=${APP_POSTGRES_PASSWORD}
    volumes:
      - app_data:/var/lib/postgresql/data
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      # ...add any required env vars for auth backend...
    depends_on:
      - postgres-app
  ngo:
    build:
      context: ./ngo-backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://${APP_POSTGRES_USER}:${APP_POSTGRES_PASSWORD}@postgres-app:5432/${APP_POSTGRES_DB}?schema=public
    depends_on:
      - postgres-app
  school-backend:
    build:
      context: ./school-backend
      dockerfile: Dockerfile
    environment:
      - GOOGLE_BOOKS_API_KEY=${GOOGLE_BOOKS_API_KEY}
      - DATABASE_URL=postgresql://${APP_POSTGRES_USER}:${APP_POSTGRES_PASSWORD}@postgres-app:5432/${APP_POSTGRES_DB}?schema=public
      - NODE_ENV=development
    depends_on:
      - postgres-app
  donor-backend:
    build:
      context: ./donor-backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://${APP_POSTGRES_USER}:${APP_POSTGRES_PASSWORD}@postgres-app:5432/${APP_POSTGRES_DB}?schema=public
    depends_on:
      postgres-app:
        condition: service_healthy
  batch-process:
    build:
      context: ./batch-process
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://${APP_POSTGRES_USER}:${APP_POSTGRES_PASSWORD}@postgres-app:5432/${APP_POSTGRES_DB}?schema=public
      - SYSTEM_TOKEN=${SYSTEM_TOKEN}
    depends_on:
      - postgres-app
  message-backend:
    build:
      context: ./messaging-job
      dockerfile: Dockerfile
    environment:
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - PORT=5005
    depends_on:
      - postgres-app
volumes:
  postgres_data:
  app_data: